# Generated by Django 4.2.13 on 2024-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postings",
            name="url_generated",
            field=models.CharField(
                default="fe78f12343f64b36beb575eaa33e322f", max_length=255, unique=True
            ),
        ),
    ]
