# Generated by Django 4.2.13 on 2024-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_postings_url_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postings",
            name="url_generated",
            field=models.CharField(
                default="47bc977b97344dd598066af87d4b76de", max_length=255, unique=True
            ),
        ),
    ]
