# Generated by Django 4.2.13 on 2024-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_postings_url_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="postings",
            name="job_title",
            field=models.CharField(default="SWE", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postings",
            name="url_generated",
            field=models.CharField(
                default="0d6aaf74610e466599ed236246f5f11c", max_length=255, unique=True
            ),
        ),
    ]
