# Generated by Django 4.2.13 on 2024-07-26 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_postings_job_title_alter_postings_url_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postings",
            name="url_generated",
        ),
        migrations.AddField(
            model_name="postings",
            name="date_posted",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
