# Generated by Django 4.2.13 on 2024-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postings",
            name="job_description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="postings",
            name="job_title",
            field=models.CharField(max_length=200),
        ),
    ]
