# Generated by Django 4.2.13 on 2024-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_postings_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postings",
            name="job_description",
            field=models.CharField(max_length=3000),
        ),
    ]
