# Generated by Django 4.2.13 on 2024-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applications",
            name="id",
        ),
        migrations.AddField(
            model_name="applications",
            name="applicant_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
