# Generated by Django 4.2.13 on 2024-07-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Applications",
        ),
    ]
